wip: implement adaptive layout
kfactory-dev/kf-website pull request #7
Opened 2021-12-31 19:22 UTC by mpontus

2022-01-04 00:42 UTC, mpontus commented
Thus branch currently features an adaptive wireframe layout built with [Rebass](https://github.com/rebassjs/rebass): https://deploy-preview-7--kf-web.netlify.app/

Next is to replace Rebass with Fabric.

2022-01-04 09:18 UTC, onnovisser reviewed
Nice. Looking good. One thing I'd add is [gatsby-plugin-styled-components](https://www.gatsbyjs.com/plugins/gatsby-plugin-styled-components/), so the styles are pre-rendered.

2022-01-04 13:51 UTC, onnovisser approved these changes
👍

2022-01-09 11:40 UTC, lucasvo requested changes

2022-01-09 11:40 UTC, lucasvo commented on src/pages/index.js
> +    text: `How to Guides`,
@mpontus This should probably be removed?

2022-01-09 14:20 UTC, merged